name: vector_indexer_agent
version: 1.0.0
description: |
  向量索引智能体
  负责将文档内容向量化并添加到FAISS索引中，
  支持向量索引管理、删除和重建。

capabilities:
  - 文本向量化（使用DashScope Embeddings）
  - FAISS索引管理
  - 批量文档索引
  - 软删除（标记删除，不影响现有索引）
  - 索引重建（清理已删除的文档）
  - 索引统计信息

dependencies:
  - src.vector.embed_service.EmbeddingService
  - src.vector.vector_store.FAISSVectorStore
  - src.service.vector_service.VectorService
  - langchain_community.embeddings.DashScopeEmbeddings
  - faiss

input_format:
  type: object
  properties:
    documents:
      type: array
      items:
        type: object
        properties:
          page_content:
            type: string
          metadata:
            type: object
      description: 文档列表
    file_id:
      type: string
      description: 文件ID（用于软删除）
    operation:
      type: string
      enum: [add, delete, rebuild, stats]
      default: add
      description: 操作类型

output_format:
  type: object
  properties:
    success:
      type: boolean
      message:
      type: string
      stats:
        type: object
        properties:
          total_vectors:
            type: integer
          active_vectors:
            type: integer
          deleted_vectors:
            type: integer

workflow:
  add:
    - step: embed_documents
      description: 文档向量化
      handler: embed_batch
    - step: add_to_index
      description: 添加到FAISS索引
      handler: add_documents
    - step: save_index
      description: 保存索引
      handler: save_index
  delete:
    - step: mark_deleted
      description: 标记文档为已删除
      handler: delete_documents
    - step: save_deleted_ids
      description: 保存已删除ID
      handler: _save_deleted_ids
  rebuild:
    - step: collect_active_docs
      description: 收集所有活跃文档
      handler: _collect_active_documents
    - step: create_new_index
      description: 创建新索引
      handler: _create_new_index
    - step: add_active_docs
      description: 添加活跃文档到新索引
      handler: add_documents
    - step: clear_deleted_ids
      description: 清除已删除ID
      handler: _clear_deleted_ids

error_handling:
  StorageError:
    message: 索引存储失败
    action: 记录日志，重试最多3次
  EmbeddingError:
    message: 向量化失败
    action: 记录日志，跳过失败文档

performance:
  batch_size: 100
  embedding_dimension: 1536
  max_retries: 3
  index_path: data/faiss_index
